name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ORGANIZATION: kirimemail
  IMAGE_NAME: frankenphp-extended

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.2, 8.3, 8.4]
        variant: [alpine, '']
        include:
          - php-version: 8.2
            php-tag: php82
          - php-version: 8.3
            php-tag: php83
          - php-version: 8.4
            php-tag: php84
          - variant: alpine
            variant-tag: alpine
          - variant: ''
            variant-tag: ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Prepare tag
        id: prep
        run: |
          PHP_TAG=${{ matrix.php-tag }}
          VARIANT_TAG=${{ matrix.variant-tag }}
          if [ -n "$VARIANT_TAG" ]; then
            FULL_TAG="${PHP_TAG}-${VARIANT_TAG}"
          else
            FULL_TAG="${PHP_TAG}"
          fi
          echo "full_tag=${FULL_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.${{ matrix.php-tag }}${{ matrix.variant-tag != '' && '.' || '' }}${{ matrix.variant-tag }}"
          tags: |
            ${{ env.DOCKER_HUB_ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.full_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max